version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: minhaSenha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"